CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255),
  imageuri VARCHAR(1000),
  image BLOB,
  price DOUBLE NOT NULL
  );